version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-container
    volumes:
      -./database:/var/lib/mysql
    ports:
      -3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}