version: '3.8'

services:
  db:
    image: 'postgres:16.2-alpine'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:  
      - "${DB_PORT}:5432"
    volumes:
      - ./database:/var/lib/postgresql